spring:
  application:
    name: users
  redis:
    host: localhost
    password:
    port: 6379
    session:
      store-type: redis
      redis:
        flush-mode: on_save
        namespace: spring:session
  rabbitmq:
    host: localhost
    username: user
    password: "bitnami"
    port: 5672
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
